### ISSUE TITLE
Add support for custom backends

### ISSUE THREAD

**Issue by sosthene-nitrokey** [trussed-dev/pc-usbip-runner#22]

**Comment by nickray** [comment]
If you come up with a smart proc-macro (or even just macro by example) for implementing a `Backends` struct, would be neat to have that upstream in the `serde_extensions` submodule.

**Comment by robin-nitrokey** [comment]
I have a derive macro for `Dispatch`.  I’ll try to expand it for `ExtensionDispatch`.

```rust
#[derive(Default, trussed::backend::Dispatch)]
#[dispatch(platform = "Platform", backend_id = "Backend")]                                               
struct Dispatch {
    test: TestBackend,
} 
```

**Comment by sosthene-nitrokey** [comment]
Maybe a simpler solution would be to pre-generate a bunch of  `Dispatch` implementations for `(A,B, …) where A: Backend, B: Backend …`

**Comment by robin-nitrokey** [comment]
That might work for `Dispatch` but I think it will not be sufficient for `ExtensionDispatch`.  And if we derive one, we can derive both.

**Comment by robin-nitrokey** [comment]
See https://github.com/trussed-dev/trussed/pull/98 for the derive macros.
